on:
  issue_comment:
    types: created

jobs:
  previewer:
    runs-on: ubuntu-latest
    steps:
      - uses: pandas-dev/github-doc-previewer@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          server: "http://135.125.134.118:8001"
          job: "Doc Build and Upload"
