on:
  issue_comment:
    types: created

jobs:
  previewer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.issue.pull_request && github.event.comment.body == '/preview'
    steps:
      - uses: pandas-dev/github-doc-previewer@master
        with:
          previewer-server: "https://pandas.pydata.org"
          artifact-job: "Doc Build and Upload"
